# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "run aws cli and install in image"
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name job-infra
              --region=us-east-1 \
workflows:
  # Name the workflow "welcome"
  run_and_set_aws_image:
    # Run the welcome/run job in its own container
    jobs:
      - create_infrastructure:
          context: pipeline_project_1
